parameters:
    php_fast_cache.cache.class: phpFastCache\Bundle\Service\Cache

services:
    phpfastcache:
        class: "%php_fast_cache.cache.class%"
        arguments:
            - "%phpfastcache%"