parameters:
    php_fast_cache.cache.class: phpFastCache\Bundle\Service\Cache
    php_fast_cache.data_collector.class: phpFastCache\Bundle\DataCollector\CacheCollector
    php_fast_cache.human_readable.class: phpFastCache\Bundle\Twig\HumanReadableExtension

services:
    phpfastcache:
        class: "%php_fast_cache.cache.class%"
        arguments:
            - "%phpfastcache%"

    phpfastcache.request_collector:
        class: "%php_fast_cache.data_collector.class%"
        arguments:
            - "@phpfastcache"
        public: false
        tags:
            -
                name:     data_collector
                template: '@phpFastCache/data_collector/template.html.twig'
                id:       'phpfastcache'
                priority: 300

    phpfastcache.human_readable_size:
        class: "%php_fast_cache.human_readable.class%"
        tags:
            - { name: twig.extension }