parameters:
    php_fast_cache.data_collector.class: Phpfastcache\Bundle\DataCollector\CacheCollector

services:
    phpfastcache.request_collector:
        class: "%php_fast_cache.data_collector.class%"
        arguments:
            - '@Phpfastcache\Bundle\Service\Cache'
        public: false
        tags:
            -
                name:     data_collector
                template: '@Phpfastcache/data_collector/template.html.twig'
                id:       'phpfastcache'
                priority: 300
