language: php

services:
  - redis-server

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="3.4.*"
    - php: nightly
      env: SYMFONY_VERSION="3.4.*"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER="weak_vendors"

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv rehash; fi;
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - composer update --no-interaction --no-progress $COMPOSER_FLAGS

before_script:
- mkdir Phpfastcache && ln -s ../ Phpfastcache/PhpfastcacheBundle