parameters:
    php_fast_cache.data_collector.class: Phpfastcache\Bundle\DataCollector\CacheCollector

services:
    data_collector.phpfastcache:
        class: "%php_fast_cache.data_collector.class%"
        arguments:
            - '@Phpfastcache\Bundle\Service\Phpfastcache'
        public: false
        tags:
            -
                name:     data_collector
                template: "@Phpfastcache/Collector/cache.html.twig"
                id:       'phpfastcache'
                priority: 300
